name: Build and Deploy Node.js to Azure Web App

on:
  push:
    branches: [ "Azure" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: skyt
  AZURE_WEBAPP_PACKAGE_PATH: './04. WebApp/Backend'
  NODE_VERSION: '22.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install dependencies
      run: npm install

    - name: Build TypeScript
      run: npm run build

    - name: Run tests (if any)
      run: npm run test --if-present

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
